---
# Rmarkdown header. it use Use the YAML syntax. 
# Just copy the ---YAML block --- and change title, subtyle, author and date
title: "Template" 
subtitle: "People Analytics"
author: "Jesús García Romanos"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide

# store the output in the subdirectory reports
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_dir=here::here("reports")) }) 
---

# Setup

*The setup chunk is hidden, change the first line to include=TRUE to show it*

```{r setup, include=FALSE}
#this chunk is hidden from the notebook output by adding ,include=FALSE to the chunk name.

library(tidyverse) 

library(here)


```

The following icons are used in the class exercises.

✍️ Your task.
📝️ R commands.
🔁 Alternative ways of doing things.
🔦 Information.
💡 Deep dive.  
🔥 This topic can be challenging—feel free to reach out with any questions.

# Section Title

```{r}

```

